name: Kernel Build (Hybrid)

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: "Kernel Name"
        required: true
        default: "MIUI-A12-NOS"
      defconfig:
        description: "Defconfig"
        required: true
        default: "surya_defconfig"
      enable_experimental:
        description: "Enable Experimental Features"
        required: false
        default: "false"
      disable_debug:
        description: "Disable Debug Configs"
        required: false
        default: "false"

env:
  BUILD_USER: fannndi
  BUILD_HOST: github
  ARCH: arm64
  SUBARCH: arm64
  CLANG_TRIPLE: aarch64-linux-gnu-

jobs:
  build:
    name: Compile Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3

      - name: Set Timezone & Vars
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          BUILD_TIME=$(date '+%d%m%Y-%H%M')
          BUILD_ID=$(date '+%Y%m%d%H%M%S')
          ZIPNAME="${{ github.event.inputs.kernel_name }}-Surya-${BUILD_TIME}.zip"
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
          echo "ZIPNAME=$ZIPNAME" >> $GITHUB_ENV
          echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV
          echo "DISABLE_DEBUG=${{ github.event.inputs.disable_debug }}" >> $GITHUB_ENV
          echo "ENABLE_EXPERIMENTAL=${{ github.event.inputs.enable_experimental }}" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git log --pretty=format:'%h - %s' -1)" >> $GITHUB_ENV

      - name: Create Swap
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            gcc-9 g++-9 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            bc binutils build-essential cmake curl git \
            kmod libelf-dev libssl-dev libncurses5-dev libncursesw5-dev \
            lzop python-is-python3 rsync unzip xz-utils zip cpio \
            lz4 device-tree-compiler libxml2-utils abootimg \
            android-sdk-libsparse-utils make ninja-build zstd \
            libzstd-dev libfdt-dev gettext libudev-dev

      - name: Install Bison 3.0.5 & Flex 2.6.4
        run: |
          mkdir -p tools && cd tools
          wget https://ftp.gnu.org/gnu/bison/bison-3.0.5.tar.gz
          tar -xf bison-3.0.5.tar.gz && cd bison-3.0.5
          ./configure --prefix=$HOME/.local && make -j$(nproc) && make install
          cd ..
          wget https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
          tar -xf flex-2.6.4.tar.gz && cd flex-2.6.4
          ./configure --prefix=$HOME/.local && make -j$(nproc) && make install
          cd ..
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$HOME/.local/lib:$HOME/.local/lib64" >> $GITHUB_ENV
          unset BISON_PKGDATADIR

      - name: Download Clang r536225
        run: |
          mkdir -p clang
          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r536225.tar.gz -O - | tar -xz -C clang
          echo "$GITHUB_WORKSPACE/clang/bin" >> $GITHUB_PATH
          echo "TOOLCHAIN_PATH=$GITHUB_WORKSPACE/clang" >> $GITHUB_ENV

      - name: Show Clang Version
        run: clang/bin/clang --version

      - name: Download GCC 9.3 (aarch64)
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-9.3 gcc64
          echo "$GITHUB_WORKSPACE/gcc64/bin" >> $GITHUB_PATH

      - name: Download GCC 4.9 (arm32)
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 gcc32
          echo "$GITHUB_WORKSPACE/gcc32/bin" >> $GITHUB_PATH

      - name: Clean Output
        run: rm -rf out dtb.img Image.gz-dtb AnyKernel3 *.zip log.txt || true

      - name: Generate Defconfig
        run: |
          make O=out ARCH=arm64 SUBARCH=arm64 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-androideabi- \
            CC=clang ${{ github.event.inputs.defconfig }}
          make O=out ARCH=arm64 SUBARCH=arm64 CC=clang olddefconfig

      - name: Apply Debug & Experimental Options
        run: |
          chmod +x scripts/config
          if [[ "${{ env.DISABLE_DEBUG }}" == "true" ]]; then
            scripts/config --file out/.config --disable DEBUG_INFO
          fi
          if [[ "${{ env.ENABLE_EXPERIMENTAL }}" == "true" ]]; then
            scripts/config --file out/.config --enable DEBUG_FS
          fi
          make O=out ARCH=arm64 SUBARCH=arm64 CC=clang olddefconfig

      - name: Compile Kernel
        run: |
          export PATH="$GITHUB_WORKSPACE/clang/bin:$GITHUB_WORKSPACE/gcc64/bin:$GITHUB_WORKSPACE/gcc32/bin:$PATH"
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          export KBUILD_COMPILER_STRING="$(clang --version | head -n1)"
          export KBUILD_BUILD_USER=$BUILD_USER
          export KBUILD_BUILD_HOST=$BUILD_HOST

          JOBS=$(nproc --ignore=1)
          export MAKEFLAGS="-j$JOBS -Oline"

          echo "🔧 Using Clang: $KBUILD_COMPILER_STRING"
          echo "🧱 Starting Kernel Build at $(date)"

          nice -n10 make O=out \
            ARCH=arm64 SUBARCH=arm64 \
            CC=clang \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            LLVM=1 LLVM_IAS=1 \
            KCFLAGS="-Wno-error" \
            KBUILD_VERBOSE=2 V=1 \
            Image.gz-dtb 2>&1 | tee log.txt

      - name: Save Final .config Snapshot
        run: cp out/.config defconfig_snapshot.config

      - name: Generate Kernel Image
        run: |
          cat out/arch/arm64/boot/Image.gz out/arch/arm64/boot/dts/**/*.dtb > Image.gz-dtb || true
          find out/arch/arm64/boot/dts -name '*.dtb' | sort | xargs cat > dtb.img || true

      - name: Package with AnyKernel3
        run: |
          git clone --depth=1 https://github.com/rinnsakaguchi/AnyKernel3 -b FSociety
          cp Image.gz-dtb dtb.img AnyKernel3/ 2>/dev/null || true
          cd AnyKernel3 && zip -r9 ../${{ env.ZIPNAME }} . -x '*.git*' README.md *placeholder

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ env.BUILD_ID }}
          path: |
            log.txt
            out/.config
            defconfig_snapshot.config
            ${{ env.ZIPNAME }}

      - name: Final Build Info
        if: success()
        run: |
          echo "✅ Build Finished!"
          echo "🕒 Duration: $(( $(date +%s) - ${{ env.BUILD_START }} ))s"
          du -sh "${{ env.ZIPNAME }}"
          sha1sum "${{ env.ZIPNAME }}"

      - name: Disable Swap
        if: always()
        run: sudo swapoff /swapfile
